name: "build-test"
on:
  create: {}
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - name: build-test
      run: |
        npm install
        npm run all
    - name: Check that the working dir is clean
      run: output=$(git status --porcelain) && ([ -z "$output" ] || (echo 'Working directory is not clean - make sure you ran `npm run all` and committed the result'; echo $output; false))
    - name: Create deployment
      uses: jackwickham/create-deployment-action@main
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        token: ${{ github.token }}
